### ISSUE TITLE
New monitor min-max-avg-Gauge

### ISSUE THREAD

**Issue by kbilsted** [mvno/Okanshi#105]
problem: A function I was measuring performance on, took a payload. By accident I found occasional high spikes in processing time and input-payload for the function from around 2-10 k input to 500k input! 

I need to continuously monitor said function as its part of our middle ware -  so I am interested in knowing the average processing speed but also understand the payload sizes. I think I best do this using an avg-max gauge. 

solution: Introduce a bit more general gauge - a combination of 3 gauges, doing min-max-avg in one sitting.

I'd be happy to implement it if we can agree it be part of the distribution.

**Comment by kichristensen** [comment]
I think it would be a great addition

**Comment by kbilsted** [comment]
I'll look into it
