### ISSUE TITLE
The Okanshi.Endpoint registers a poller on DefaultMonitorRegistry.Instance leading to unexpected readings when setting up your own  poller

### ISSUE THREAD

**Issue by kbilsted** [mvno/Okanshi#121]
lets discuss the best solution

**Comment by kichristensen** [comment]
I think we should pass in a poller when creating the endpoint

**Comment by kbilsted** [comment]
Or perhaps a registry should contain a poller to ensure we do not get several pollers for a registry?

**Comment by kichristensen** [comment]
I think that is a different problem, or at least the title of this issue is wrong if that is what we want to solve
