### ISSUE TITLE
forskel på en PeakRateCounter og en count på en basictimer

### ISSUE THREAD

**Issue by kbilsted** [mvno/Okanshi#20]
Hej @kichristensen 

![image](https://cloud.githubusercontent.com/assets/1616338/22639028/3db6e820-ec4c-11e6-87db-fdb916900049.png)

viser to ens grafer. Pånær y-aksen. Den øverste graf er en `count` af en `BasicTimer` den nederste er en 
`PeakRateCounter`

Er det en fejl eller mangler der blot noget dokumentation ?

**Comment by kichristensen** [comment]
@kbilsted det er meningen. Forskellen er at BasicTimer både måler gennemsnits eksekverings tiden og derfor også antallet af kald, som også bliver udstillet. PeakRateCounter gemmer kun antallet.

**Comment by kbilsted** [comment]
men hvorfor er der en faktor 60 i forskel på dem? og bør det ikke fremgå af dokumentationen?

**Comment by kichristensen** [comment]
@kbilsted fordi timeren viser antallet af kald pr sekund i den version i bruger. Vi den nye version, som i ikke bruger endnu, mener jeg det er ændret til at være det reelle antal kald indenfor minuttet

**Comment by kbilsted** [comment]
ok
