### ISSUE TITLE
for dårlig opløsning på målinger

### ISSUE THREAD

**Issue by kbilsted** [mvno/Okanshi#21]
hej jeg tror der er et problem med at måle meget korte tidsserier.

Jeg måler udførelsen af en controller

```
	public class CheckController : ApiController
	{
		[HttpGet]
		public HttpResponseMessage Get(...)
		{
			ServiceHost.RequestIsFeatureEnabled.Record(() => new CheckFeature(GetAllFeatures()).IsEnabled(...));

			return new HttpResponseMessage(HttpStatusCode.OK) { ... };
		}
	}
```

postman siger  23 ms

![postman](https://cloud.githubusercontent.com/assets/1616338/22697343/6dc0a9d8-ed51-11e6-8cbc-a7e416cc4b2d.png)

okanshi siger 60 ms (der er to spikes helt til højre, det er kun den sidste jeg refererer til her i denne bugrequest ;)

![okanshi](https://cloud.githubusercontent.com/assets/1616338/22697399/9b5dcd30-ed51-11e6-9556-657bfcebe4ed.png)

Jeg har flere målinger der bekræftiger at tiden postman viser (som er inkl. http og dermed være større) end de tal jeg aflæser i inlfux. I influx hvor jeg tager tid på flere kald summer de i influx næsten til 60 ms.

**Comment by kichristensen** [comment]
@kbilsted jeg skal se hele opsætningen af de forspørgsel i Chronograf for at kunne hjælpe dig

**Comment by kichristensen** [comment]
En BasicTimer udstiller flere statistikker, blandt andet min, max og average. I din forespørgsel har du ikke defineret hvilken statistik du vil se, hvorfor tallet ikke giver nogen mening.
Der findes et tag der hedder statistic, hvor du skal vælge hvad der giver mening, i din tilfælde er det nok avg for average

**Comment by kbilsted** [comment]
du har da så ret. Jeg syntes jeg havde leget med de forskellige stats men fik tit noget forkert - måske fordi jeg fik rodet mig ud i også at sætte `dataSource`  - og fordi denne måling er så hurtig at avg for testsystemet giver 0 - så tænker man altid der er noget galt.. men hvis det tager 20 ms fra min maskine er det serverdelen laver nok meeeget få millist... faktisk gennemløber den en liste på ca 15 rækker og kalder noget simpel string-matching.. Jeg ser i prod at den ligger på 0-6 ms... tager jeg tid for klienten at ramme min service og så svar ligger tiden oftens på en 5-6 ms men med 3 spikes på 75 ms over de sidste 5 dage. om 75 ms er ok for et restkald er jeg ikke helt klar over- men det lyder af meget.. men det har jo ikke lige noget med okanshi at gøre ;)
