### ISSUE TITLE
github tags

### ISSUE THREAD

**Issue by kbilsted** [mvno/Okanshi#61]
github now supports tags for grouping projects. We should add tags such as 

metrics
dotnetcore
health-check
monitoring
performance
dotnet
instrumentation
application-insights
dotnet-core
dotnet-standard
dotnet-framework
influx-db

**Comment by kichristensen** [comment]
@ChristianTrolleMikkelsen Can you take a look at this? I don't have the rights to do this

**Comment by kbilsted** [comment]
me neither... ;-P

**Comment by ChristianTrolleMikkelsen** [comment]
You now have admin rights to do it :)

**Comment by kichristensen** [comment]
Tags have been added
