### ISSUE TITLE
document healthcheck as monitor

### ISSUE THREAD

**Issue by kbilsted** [mvno/Okanshi#76]
in the tutorial it states

> As of version 4 health checks can also be registered as a monitor. This is done like this:

please explain the difference to using the monitor and the health check. Both seem to be a func -> bool

**Comment by kbilsted** [comment]
Also registering 

	        OkanshiMonitor.HealthCheck(() => Directory.GetFiles("C:\\temp").Length == 0, "NoFilesInDirectory", new Tag[0]);

the code does not get invoked when i access the healthcheck endpoint

**Comment by kichristensen** [comment]
Is this better?

**Comment by kbilsted** [comment]
closing. We simplify the api instead
