### ISSUE TITLE
Discuss how to do timing

### ISSUE THREAD

**Issue by kbilsted** [mvno/Okanshi#79]
nice reading material

https://stackoverflow.com/questions/5113750/net-system-diagnostics-stopwatch-issue-returns-values-too-low

**Comment by kichristensen** [comment]
Reading the StackOverflow post, it doesn't seem that anything can be concluded that would require us to change it. This issue will be closed, but can be reopened if needed

**Comment by kbilsted** [comment]
one advice on that link

> As for the solution to this problem... I haven't found one in a lot of googling. You can ignore values less than zero, which is not ideal but workable in some cases.

should we do the same?

that is also suggested here https://stackoverflow.com/questions/1008345/system-diagnostics-stopwatch-returns-negative-numbers-in-elapsed-properties  

lol some dude decompiled stopwatch... it appears it does this by default in 4.0

public void Stop()
{
    if (this.isRunning)
    {
        long num2 = GetTimestamp() - this.startTimeStamp;
        this.elapsed += num2;
        this.isRunning = false;
        // THE NEXT 4 LINES ARE NEW IN .NET 4.0:
        if (this.elapsed < 0L)
        {
            this.elapsed = 0L;
        }
    }
}

leave this closed.. ;)
